### ISSUE TITLE
Remove TaskScheduler::task

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/task#10]
This seems to be a direct duplicate of `Task::async`. There should be only one way to avoid confusion and maintenance overhead.

**Comment by martinschroeder** [comment]
You are right about the duplication. The only reason for the existence of the `task()` method is that i need to pin tasks to a task scheduler at the time of construction. Therefore that method is required for the current API.

I will begin work on a default scheduler and global root context soon, this will be a way of removing the `task` method in the future.
