### ISSUE TITLE
Error: Only tasks can be waited when no scheduler is running

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/task#18]
I'm currently getting `Error: Only tasks can be waited when no scheduler is running` while running the tests for the ported `amphp/process`. Seems like it's currently not possible to await `Awaitable` instances, only `Task` instances?

**Comment by kelunik** [comment]
It happens for example if I remove [this](https://github.com/amphp/amp/blob/5b7d5bdafb6cec78ba31cb0f4d428fc12a99e396/examples/coroutines/concurrency.php#L34) and [that](https://github.com/amphp/amp/blob/5b7d5bdafb6cec78ba31cb0f4d428fc12a99e396/examples/coroutines/concurrency.php#L41) line. Guess I always need a wrapping `Task::await(Task::async(...));` for now? But it also happens in tests that have `Task::await(Task::async(...));` around somehow.

**Comment by martinschroeder** [comment]
I added support for arbitrary `Awaitable` objects to `await()` when no scheduler is running. Not sure if this fixes your problem, but it is a nice addition.

**Comment by martinschroeder** [comment]
I tried your example with and without removed lines and it works just fine for now. I also added the defer watcher to your task scheduler and there were no problems at all so far.

**Comment by martinschroeder** [comment]
@kelunik The only thing i did was to add this in the scheduler:
```php
proetcted function activate()
{
    Loop::defer(function () {
        $this->dispatch();
    });
}
```

**Comment by kelunik** [comment]
@martinschroeder After your latest changes, `Loop::defer(Closure::fromCallable([$this, 'dispatch']));` should also be fine, right?

**Comment by martinschroeder** [comment]
Yes, i specifically made that change to allow for this little optimzation with amp's defer watchers.
