### ISSUE TITLE
Top-level await behaves weird

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/task#23]
```php
<?php

require __DIR__ . '/../../vendor/autoload.php';

use Concurrent\Task;
use function Amp\delay;

// Shows how two for loops are executed concurrently.

// Note that the first two items are printed _before_ the Loop::run()
// as they're executed immediately and do not register any timers or defers.

function printWithTime(string $message): void
{
    static $start = null;
    $start = $start ?? microtime(true);

    printf("%' 4d ms ", round((microtime(true) - $start) * 1000));

    print $message . PHP_EOL;
}

printWithTime("-- begin task A --");
$a = Task::async(function () {
    for ($i = 0; $i < 8; $i++) {
        printWithTime(" A :: " . $i);
        delay(1000);
    }

    printWithTime("-- end of task A --");
});

printWithTime("-- begin task B --");
for ($i = 0; $i < 3; $i++) {
    printWithTime("           B :: " . $i);
    delay(2000);
}

printWithTime("-- end of task B --");

Task::await($a);
```

I expected the above code to have the same output as [this script](https://github.com/amphp/amp/blob/7fc47f3df3def839b600eedfbc5e717b5ce78e49/examples/coroutines/concurrency.php).

**Comment by martinschroeder** [comment]
I adjusted the await method to call the new stopLoop() method as soon as an awaitable that is awaited by the main execution resolves. Can you try your example again and check if it is working as expected now?

**Comment by kelunik** [comment]
@martinschroeder Why stop it? Can't we make the `runLoop()` a fiber that's paused in that case?

**Comment by kelunik** [comment]
It works fine, thanks! Did you think about the alternative approach I mentioned?

**Comment by martinschroeder** [comment]
Yes i been thinking about that. It should be doable but i was focusing on creating a solution that would not need such a huge change to the inner workings of the scheduler at this time. At some point in time i want to create a more efficient scheduler (see #4), i think this will be the right time to look into the event loop integration again.
