### ISSUE TITLE
Fully async programs / long running apps

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/task#24]
It would be good to have something that replaces a top-level `Loop::run` for long-running applications.

Maybe `TaskScheduler::awaitRuntimeEnd()`? Maybe also make it continue to run by default and require an explicit stop if it should stop at the script's end.

**Comment by martinschroeder** [comment]
The task scheduler will now automatically run to completion when the main execution is terminated. This will run the loop as a shutdown function. I am still looking for a way to run it a little bit sooner... no luck so far.

**Comment by kelunik** [comment]
I guess we'd need core support for that? Can we maybe sneak that into PHP 7.3, so we can base an Amp v3 on `ext-task` for testing for inclusion in 7.4 / 8.0? A shutdown function unfortunately is a bad combination with `exit`.

**Comment by martinschroeder** [comment]
I just pushed a commit that solves the problem. I added a custom executor function to have the scheduler run before PHP's shutdown sequence (including user-defined shutdown functions) is started. You can verify this in example `b.php` which prints a little message in a shutdown function.

**Comment by kelunik** [comment]
Seems to work fine, yes.
